### ISSUE TITLE
InternalOpenIDError: Failed to discover OP endpoint URL 

### ISSUE THREAD

**Issue by L1mit1337** [SwaggyMacro/cs2-WeaponPaints-Website#2]
![屏幕截图 2024-03-26 211022](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/f8d0fc56-a8b7-448e-91ff-8faf8b42631d)
 
不知道什么原因的报错 node.js v17.9.1

**Comment by SwaggyMacro** [comment]
passport库需要去获取Steam的API接口地址，这部分操作需要网络可以直接访问steam才行，后续考虑修改一下

**Comment by L1mit1337** [comment]
> passport库需要去获取Steam的API接口地址，这部分操作需要网络可以直接访问steam才行，后续考虑修改一下

境外的服务器应该可以吧

**Comment by SwaggyMacro** [comment]
> > passport库需要去获取Steam的API接口地址，这部分操作需要网络可以直接访问steam才行，后续考虑修改一下
> 
> 境外的服务器应该可以吧

可以

**Comment by wudi-7mi** [comment]
请问对此有什么暂时的解决方法吗？
