### ISSUE TITLE
code :  1 message :  "Session ID unknown"

### ISSUE THREAD

**Issue by L1mit1337** [SwaggyMacro/cs2-WeaponPaints-Website#3]
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/89ec7490-c45d-4d7b-af5e-f68fde58b2ac)
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/b7eef854-adea-4047-b30d-cc221f89f8f4)

[config.json]
PROTOCOL:http Port:80

这个是网站:http://csl1mit.icu/   虽然登录之后跳转了 但是并没有成功的登录 我大概查了一下socket.io文档有说 没有开启粘性会话会导致 但是我没有node.js的开发经验无从下手。

**还有一些BUG.**
默认的配置文件中
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/16e91fc8-d5e5-4895-92a9-96bc64de77e2)
PROTOCOL项必须修改为http port必须修改为80 如果按照默认的配置开启服务器后 进入网站登录后的地址会变为 https://域名....
而且不带端口号
![屏幕截图 2024-03-27 031420](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/a3248734-5257-4184-9a22-beeaac6eb95d)

 从而被拒绝连接 而一开始进入的时候则不是https 而是http ![屏幕截图 2024-03-27 031336](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/8dbb9fc0-ece8-4185-89b1-0beb5df0dc3d)

**Comment by SwaggyMacro** [comment]
- 默认端口不是80是留给nginx反代的，我本机尝试http协议 80端口没有问题。
- 关于socket.io问题可尝试配置好ssl证书 使用https协议。
- 默认配置文件是https确实会有点问题，https默认使用443端口了，已经改成http了。
- 建议使用nginx反代nodejs项目，宝塔或1panel可以一键配置。
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/38845682/eb9ae90c-ac17-46c4-9ea6-deba04691880)

**Comment by L1mit1337** [comment]
> 默认端口不是80是留给nginx反代的，我本机尝试http协议 80端口没有问题。 ![image](https://private-user-images.githubusercontent.com/38845682/317118585-eb9ae90c-ac17-46c4-9ea6-deba04691880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTIyNzgsIm5iZiI6MTcxMTUxMTk3OCwicGF0aCI6Ii8zODg0NTY4Mi8zMTcxMTg1ODUtZWI5YWU5MGMtYWMxNy00NmM0LTllYTYtZGViYTA0NjkxODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzNTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZjIyOTVkYTY0MTA4OTM3N2QzYWVlZTU2NjY5NzhjZGIzNGFlZGY3NDQzMTVhNzBlNWQzNTk5YzdlNTcwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdpFTTTZqGkMC90i-20b

> * 默认端口不是80是留给nginx反代的，我本机尝试http协议 80端口没有问题。
> * 关于socket.io问题可尝试配置好ssl证书 使用https协议。
> * 默认配置文件是https确实会有点问题，https默认使用443端口了，已经改成http了。
> * 建议使用nginx反代nodejs项目，宝塔或1panel可以一键配置。
>   ![image](https://private-user-images.githubusercontent.com/38845682/317118585-eb9ae90c-ac17-46c4-9ea6-deba04691880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTI0MDMsIm5iZiI6MTcxMTUxMjEwMywicGF0aCI6Ii8zODg0NTY4Mi8zMTcxMTg1ODUtZWI5YWU5MGMtYWMxNy00NmM0LTllYTYtZGViYTA0NjkxODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA0MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MGJiYWQwOTllMTAzZmJiZDUwYWI5MzAxY2Q0MDU3OTYwYjUwZGM2ZThmMGYxNmZjNjI0ZDI1ZjE0NTM2MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhkxjHyPCss14U3wBGfikOACEf1qyppawkH9ZNSvxsw)

好的我去试一下 昨天给我整麻了 昨天我也在尝试解决socket.io 的问题 生成了公钥私钥 但是不知道在哪里配置 我没在app.js中看到相关代码 我怕改出问题

**Comment by SwaggyMacro** [comment]
https问题可以直接使用nginx反代，在nginx中配置ssl证书即可。

**Comment by SwaggyMacro** [comment]
Demo站：[cs.ncii.cn](https://cs.ncii.cn/)

**Comment by L1mit1337** [comment]
> Demo站：[cs.ncii.cn](https://cs.ncii.cn/)

这个demo站是搭建在国内的吗？ 我也有台国内的服务器 我试了 steam302 梯子 都不能跳到steam那个登录 有什么解决办法吗

**Comment by SwaggyMacro** [comment]
> > Demo站：[cs.ncii.cn](https://cs.ncii.cn/)
> 
> 这个demo站是搭建在国内的吗？ 我也有台国内的服务器 我试了 steam302 梯子 都不能跳到steam那个登录 有什么解决办法吗

服务器是海外的，cdn是国内的。可以等后续更新 或者用海外服务器

**Comment by L1mit1337** [comment]
> https问题可以直接使用nginx反代，在nginx中配置ssl证书即可。

好吧我宣布我放弃了。。。。我用了反代但是还是很多报错502之类的 有时候又可登录但是跳转回来后就还是没有登录信息 且不能修改皮肤。

**Comment by L1mit1337** [comment]
> https问题可以直接使用nginx反代，在nginx中配置ssl证书即可。

我用win端搭建成功进入了。。。。 好像linux的有点问题
![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/63892863/d6703ebf-c9b4-4bf6-8ded-9651dd365aed)

**Comment by SwaggyMacro** [comment]
linux的跟Windows差不多的，demo站点就是linux系统搭建的
