### ISSUE TITLE
InternalOpenIDError: Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by NoSetViolin** [SwaggyMacro/cs2-WeaponPaints-Website#8]
InternalOpenIDError: Failed to discover OP endpoint URL
    at E:\cs2skin\node_modules\@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
    at E:\cs2skin\node_modules\openid\openid.js:757:14
    at E:\cs2skin\node_modules\openid\openid.js:547:13
    at E:\cs2skin\node_modules\openid\openid.js:503:11
    at E:\cs2skin\node_modules\openid\http.js:41:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

![image](https://github.com/SwaggyMacro/cs2-WeaponPaints-Website/assets/130219679/3aecab7b-63d5-4741-aee7-9fa22e10e399)

**Comment by SwaggyMacro** [comment]
Duplicate #2

**Comment by NoSetViolin** [comment]
我解决这个问题了，现在可以使用，但是购买界面一买枪就炸服是怎么回事

**Comment by SwaggyMacro** [comment]
> 我解决这个问题了，现在可以使用，但是购买界面一买枪就炸服是怎么回事

购枪界面炸服是服务器或者插件问题了，网站仅仅是跟数据库有交互
